console.clear()
const box1 = document.querySelector('.box1')
const box2 = document.querySelector('.box2')
const box3 = document.querySelector('.box3')
const box4 = document.querySelector('.box4')

const buttonRotate = document.querySelector('.button-rotate')
const buttonColor = document.querySelector('.button-color')
const buttonShape = document.querySelector('.button-shape')
const buttonShrink = document.querySelector('.button-shrink')

buttonRotate.addEventListener('click', () => {
  box1.classList.remove('hidden')
  box2.classList.add('hidden')
  box3.classList.add('hidden')
  box4.classList.add('hidden')
  buttonRotate.classList.add('active')
  buttonColor.classList.remove('active')
  buttonShape.classList.remove('active')
  buttonShrink.classList.remove('active')
})
buttonColor.addEventListener('click', () => {
  box1.classList.add('hidden')
  box2.classList.remove('hidden')
  box3.classList.add('hidden')
  box4.classList.add('hidden')
  buttonRotate.classList.remove('active')
  buttonColor.classList.add('active')
  buttonShape.classList.remove('active')
  box4.classList.remove('active')
})
buttonShape.addEventListener('click', () => {
  box1.classList.add('hidden')
  box2.classList.add('hidden')
  box3.classList.remove('hidden')
  box4.classList.add('hidden')
  buttonRotate.classList.remove('active')
  buttonColor.classList.remove('active')
  buttonShape.classList.add('active')
  buttonShrink.classList.remove('active')
})
buttonShrink.addEventListener('click', () => {
  box1.classList.add('hidden')
  box2.classList.add('hidden')
  box3.classList.add('hidden')
  box4.classList.remove('hidden')
  buttonRotate.classList.remove('active')
  buttonColor.classList.remove('active')
  buttonShape.classList.remove('active')
  buttonShrink.classList.add('active')
})
