console.clear()
const box1 = document.querySelector('.box1')
const box2 = document.querySelector('.box2')
const box3 = document.querySelector('.box3')
const box4 = document.querySelector('.box4')

const buttonRotate = document.querySelector('.button-rotate')
const buttonColor = document.querySelector('.button-color')
const buttonShape = document.querySelector('.button-shape')
const buttonShrink = document.querySelector('.button-shrink')

buttonRotate.addEventListener('click', () => {
  box1.classList.toggle('show')
  box2.classList.toggle('hidden')
  box3.classList.toggle('hidden')
  box4.classList.toggle('hidden')
})
buttonColor.addEventListener('click', () => {
  box1.classList.toggle('hidden')
  box2.classList.toggle('show')
  box3.classList.toggle('hidden')
  box4.classList.toggle('hidden')
})
buttonShape.addEventListener('click', () => {
  box1.classList.toggle('hidden')
  box2.classList.toggle('hidden')
  box3.classList.toggle('show')
  box4.classList.toggle('hidden')
})
buttonShrink.addEventListener('click', () => {
  box1.classList.toggle('hidden')
  box2.classList.toggle('hidden')
  box3.classList.toggle('hidden')
  box4.classList.toggle('show')
})
